// For loading translation data

// Var makes this accessible
var LanguageLoader = 
{
	localeFilesLS :
	[
		'general_chinese(Simplified)',
		'general_chinese(Traditional)',
		'general_dutch',
		'general_english',
		'general_german',
		'general_hungarian',
		'general_italian',
		'general_japanese',
		'general_polish',
		'general_portuguese(Brazil)',
		'general_serbian',
		'general_spanish',
		'mystery001_chinese(Simplified)',
		'mystery001_chinese(Traditional)',
		'mystery001_dutch',
		'mystery001_english',
		'mystery001_german',
		'mystery001_hungarian',
		'mystery002_chinese(Simplified)',
		'mystery002_chinese(Traditional)',
		'mystery002_dutch',
		'mystery002_english',
		'mystery002_german',
		'mystery002_hungarian',
		'mystery003_chinese(Simplified)',
		'mystery003_chinese(Traditional)',
		'mystery003_dutch',
		'mystery003_english',
		'mystery003_german',
		'mystery003_hungarian',
		'mystery004_chinese(Simplified)',
		'mystery004_chinese(Traditional)',
		'mystery004_dutch',
		'mystery004_english',
		'mystery004_german',
		'mystery004_hungarian',
		'mystery005_chinese(Simplified)',
		'mystery005_chinese(Traditional)',
		'mystery005_dutch',
		'mystery005_english',
		'mystery005_german',
		'mystery005_hungarian',
		'mystery006_chinese(Simplified)',
		'mystery006_chinese(Traditional)',
		'mystery006_dutch',
		'mystery006_english',
		'mystery006_german',
		'mystery006_hungarian',
		'mystery007_chinese(Simplified)',
		'mystery007_chinese(Traditional)',
		'mystery007_dutch',
		'mystery007_english',
		'mystery007_german',
		'mystery007_hungarian',
		'mystery008_chinese(Simplified)',
		'mystery008_chinese(Traditional)',
		'mystery008_dutch',
		'mystery008_english',
		'mystery008_german',
		'mystery008_hungarian',
		'mystery009_chinese(Simplified)',
		'mystery009_chinese(Traditional)',
		'mystery009_dutch',
		'mystery009_english',
		'mystery009_german',
		'mystery009_hungarian',
		'mystery010_chinese(Simplified)',
		'mystery010_chinese(Traditional)',
		'mystery010_dutch',
		'mystery010_english',
		'mystery010_german',
		'mystery010_hungarian',
		'mystery011_chinese(Simplified)',
		'mystery011_chinese(Traditional)',
		'mystery011_dutch',
		'mystery011_english',
		'mystery011_german',
		'mystery011_hungarian',
		'mystery012_chinese(Simplified)',
		'mystery012_chinese(Traditional)',
		'mystery012_dutch',
		'mystery012_english',
		'mystery012_german',
		'mystery012_hungarian',
		'mystery013_chinese(Simplified)',
		'mystery013_chinese(Traditional)',
		'mystery013_dutch',
		'mystery013_english',
		'mystery013_german',
		'mystery013_hungarian',
		'mystery014_chinese(Simplified)',
		'mystery014_chinese(Traditional)',
		'mystery014_dutch',
		'mystery014_english',
		'mystery014_german',
		'mystery014_hungarian',
		'mystery015_chinese(Simplified)',
		'mystery015_chinese(Traditional)',
		'mystery015_dutch',
		'mystery015_english',
		'mystery015_german',
		'mystery015_hungarian',
		'mystery016_chinese(Simplified)',
		'mystery016_chinese(Traditional)',
		'mystery016_dutch',
		'mystery016_english',
		'mystery016_german',
		'mystery016_hungarian',
		'mystery017_chinese(Simplified)',
		'mystery017_chinese(Traditional)',
		'mystery017_dutch',
		'mystery017_english',
		'mystery017_german',
		'mystery017_hungarian',
		'mystery018_chinese(Simplified)',
		'mystery018_chinese(Traditional)',
		'mystery018_dutch',
		'mystery018_english',
		'mystery018_german',
		'mystery018_hungarian',
		'mystery019_chinese(Simplified)',
		'mystery019_chinese(Traditional)',
		'mystery019_dutch',
		'mystery019_english',
		'mystery019_german',
		'mystery019_hungarian',
		'mystery020_chinese(Simplified)',
		'mystery020_chinese(Traditional)',
		'mystery020_dutch',
		'mystery020_english',
		'mystery020_german',
		'mystery020_hungarian',
		'mysteryend',
		'mysteryend_chinese(Traditional)',
		'mysteryend_dutch',
		'mysteryend_english',
		'mysteryend_german',
		'mysteryend_hungarian',
		'mysteryintro_chinese(Simplified)',
		'mysteryintro_chinese(Traditional)',
		'mysteryintro_dutch',
		'mysteryintro_english',
		'mysteryintro_german',
		'mysteryintro_hungarian',
		'mysterylang'
	],
	// Loads a given file from filename (minus the .txt) into a symbol table.
	// then - callback for when the load is complete
	loadFile(file)
	{
		let symbolTable = {};

		const url = './';
		const re = /(\w+)=([^&]+)/g;

		$.ajax(
		{
			url: `${url}/locale/${file}.txt`,
			// TODO: this is not good. Use a callback instead
			async : false
		}).done(response =>
		{
			let match;
			while (match = re.exec(response))
				symbolTable[match[1]] = match[2].trim();
		});

		return symbolTable;
	}
};
